sudo: required
services:
- docker
before_install:
- docker pull lambda3/dotnet-commands
script:
- docker run -ti --rm -v "$(pwd):/app" lambda3/dotnet-commands /bin/bash -c 'cd /app && dotnet restore && cd /app/test/IntegrationTests && dotnet test'