version: 1.0.{build}

clone_folder: c:\projects\dotnet-commands

shallow_clone: true

clone_depth: 1

build_script:
  - ps: >-

      dotnet restore

      cd c:\projects\dotnet-commands\src\dotnet-commands

      dotnet build

      cd c:\projects\dotnet-commands\test\IntegrationTests

      dotnet build

test_script:
  - ps: >-

      cd c:\projects\dotnet-commands\test\IntegrationTests

      dotnet test